// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_DRIVERDISPLAY_H
#define UI_DRIVERDISPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DriverDisplay
extern void ui_DriverDisplay_screen_init(void);
extern void ui_DriverDisplay_screen_destroy(void);
extern lv_obj_t * ui_DriverDisplay;
extern lv_obj_t * ui_StatBase;
extern lv_obj_t * ui_DescriptionTag;
extern lv_obj_t * ui_StatBaseTag;
extern lv_obj_t * ui_SubTextTag;
extern lv_obj_t * ui_BaseContainer;
extern lv_obj_t * ui_CarStateContainer;
extern lv_obj_t * ui_VehicleStateLabel;
extern lv_obj_t * ui_VehicleStateText;
extern lv_obj_t * ui_CarStats;
extern lv_obj_t * ui_Power;
extern lv_obj_t * ui_PowerTag;
extern lv_obj_t * ui_PowerBaseTag;
extern lv_obj_t * ui_PowerSubTextTag;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_SpeedTag;
extern lv_obj_t * ui_SpeedBaseTag;
extern lv_obj_t * ui_SpeedSubTextTag;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_MotorTag;
extern lv_obj_t * ui_MotorBaseTag;
extern lv_obj_t * ui_MotorSubTextTag;
extern lv_obj_t * ui_Throttle;
extern lv_obj_t * ui_ThrottleTag;
extern lv_obj_t * ui_ThrottleBaseTag;
extern lv_obj_t * ui_ThrottleSubTextTag;
extern lv_obj_t * ui_StateofCharge;
extern lv_obj_t * ui_StateofChargeTag;
extern lv_obj_t * ui_SOCBaseTag;
extern lv_obj_t * ui_BatterySubTextTag;
extern lv_obj_t * ui_Brake;
extern lv_obj_t * ui_BrakeTag;
extern lv_obj_t * ui_BrakeBaseTag;
extern lv_obj_t * ui_BrakeSubTextTag;
extern lv_obj_t * ui_TemperatureContainer;
extern lv_obj_t * ui_TemperatureTag;
extern lv_obj_t * ui_TemperatureBaseTag;
extern lv_obj_t * ui_TemperatureBar;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Container1;
extern lv_obj_t * uic_TemperatureBar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

