// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_TemperatureBar;
lv_obj_t * uic_Container1;
lv_obj_t * ui_DriverDisplay = NULL;
lv_obj_t * ui_StatBase = NULL;
lv_obj_t * ui_DescriptionTag = NULL;
lv_obj_t * ui_StatBaseTag = NULL;
lv_obj_t * ui_SubTextTag = NULL;
lv_obj_t * ui_BaseContainer = NULL;
lv_obj_t * ui_CarStateContainer = NULL;
lv_obj_t * ui_VehicleStateLabel = NULL;
lv_obj_t * ui_VehicleStateText = NULL;
lv_obj_t * ui_CarStats = NULL;
lv_obj_t * ui_Power = NULL;
lv_obj_t * ui_PowerTag = NULL;
lv_obj_t * ui_PowerBaseTag = NULL;
lv_obj_t * ui_PowerSubTextTag = NULL;
lv_obj_t * ui_Speed = NULL;
lv_obj_t * ui_SpeedTag = NULL;
lv_obj_t * ui_SpeedBaseTag = NULL;
lv_obj_t * ui_SpeedSubTextTag = NULL;
lv_obj_t * ui_RPM = NULL;
lv_obj_t * ui_MotorTag = NULL;
lv_obj_t * ui_MotorBaseTag = NULL;
lv_obj_t * ui_MotorSubTextTag = NULL;
lv_obj_t * ui_Throttle = NULL;
lv_obj_t * ui_ThrottleTag = NULL;
lv_obj_t * ui_ThrottleBaseTag = NULL;
lv_obj_t * ui_ThrottleSubTextTag = NULL;
lv_obj_t * ui_StateofCharge = NULL;
lv_obj_t * ui_StateofChargeTag = NULL;
lv_obj_t * ui_SOCBaseTag = NULL;
lv_obj_t * ui_BatterySubTextTag = NULL;
lv_obj_t * ui_Brake = NULL;
lv_obj_t * ui_BrakeTag = NULL;
lv_obj_t * ui_BrakeBaseTag = NULL;
lv_obj_t * ui_BrakeSubTextTag = NULL;
lv_obj_t * ui_TemperatureContainer = NULL;
lv_obj_t * ui_TemperatureTag = NULL;
lv_obj_t * ui_TemperatureBaseTag = NULL;
lv_obj_t * ui_TemperatureBar = NULL;
// event funtions

// build funtions

void ui_DriverDisplay_screen_init(void)
{
    ui_DriverDisplay = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DriverDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatBase = lv_obj_create(ui_DriverDisplay);
    lv_obj_remove_style_all(ui_StatBase);
    lv_obj_set_width(ui_StatBase, 150);
    lv_obj_set_height(ui_StatBase, 150);
    lv_obj_set_x(ui_StatBase, -366);
    lv_obj_set_y(ui_StatBase, -49);
    lv_obj_set_align(ui_StatBase, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StatBase, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_StatBase, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatBase, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_StatBase, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_StatBase, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_StatBase, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DescriptionTag = lv_label_create(ui_StatBase);
    lv_obj_set_width(ui_DescriptionTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DescriptionTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DescriptionTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DescriptionTag, "text");
    lv_obj_set_style_text_font(ui_DescriptionTag, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatBaseTag = lv_label_create(ui_StatBase);
    lv_obj_set_width(ui_StatBaseTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatBaseTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatBaseTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatBaseTag, "text");
    lv_obj_set_style_text_font(ui_StatBaseTag, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SubTextTag = lv_label_create(ui_StatBase);
    lv_obj_set_width(ui_SubTextTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SubTextTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SubTextTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SubTextTag, "text");

    ui_BaseContainer = lv_obj_create(ui_DriverDisplay);
    lv_obj_remove_style_all(ui_BaseContainer);
    lv_obj_set_width(ui_BaseContainer, 1024);
    lv_obj_set_height(ui_BaseContainer, 600);
    lv_obj_set_align(ui_BaseContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BaseContainer, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_BaseContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_BaseContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_BaseContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BaseContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BaseContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BaseContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CarStateContainer = lv_obj_create(ui_BaseContainer);
    lv_obj_remove_style_all(ui_CarStateContainer);
    lv_obj_set_width(ui_CarStateContainer, 580);
    lv_obj_set_height(ui_CarStateContainer, 86);
    lv_obj_set_x(ui_CarStateContainer, 259);
    lv_obj_set_y(ui_CarStateContainer, -148);
    lv_obj_set_align(ui_CarStateContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CarStateContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CarStateContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_CarStateContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_CarStateContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CarStateContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CarStateContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CarStateContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VehicleStateLabel = lv_label_create(ui_CarStateContainer);
    lv_obj_set_width(ui_VehicleStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VehicleStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VehicleStateLabel, -93);
    lv_obj_set_y(ui_VehicleStateLabel, -65);
    lv_obj_set_align(ui_VehicleStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VehicleStateLabel, "Vehicle State:");
    lv_obj_set_style_text_font(ui_VehicleStateLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VehicleStateText = lv_label_create(ui_CarStateContainer);
    lv_obj_set_width(ui_VehicleStateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VehicleStateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VehicleStateText, -192);
    lv_obj_set_y(ui_VehicleStateText, -13);
    lv_obj_set_align(ui_VehicleStateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VehicleStateText, "Idle");
    lv_obj_set_style_text_font(ui_VehicleStateText, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CarStats = lv_obj_create(ui_BaseContainer);
    lv_obj_remove_style_all(ui_CarStats);
    lv_obj_set_width(ui_CarStats, 889);
    lv_obj_set_height(ui_CarStats, LV_SIZE_CONTENT);    /// 500
    lv_obj_set_x(ui_CarStats, -147);
    lv_obj_set_y(ui_CarStats, 231);
    lv_obj_set_align(ui_CarStats, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CarStats, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_CarStats, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CarStats, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_CarStats, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CarStats, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Power = lv_obj_create(ui_CarStats);
    lv_obj_remove_style_all(ui_Power);
    lv_obj_set_height(ui_Power, 250);
    lv_obj_set_width(ui_Power, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_x(ui_Power, -366);
    lv_obj_set_y(ui_Power, -49);
    lv_obj_set_align(ui_Power, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Power, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Power, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Power, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Power, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerTag = lv_label_create(ui_Power);
    lv_obj_set_width(ui_PowerTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerTag, "Power");
    lv_obj_set_style_text_font(ui_PowerTag, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerBaseTag = lv_label_create(ui_Power);
    lv_obj_set_width(ui_PowerBaseTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerBaseTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerBaseTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerBaseTag, "400");
    lv_obj_set_style_text_font(ui_PowerBaseTag, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerSubTextTag = lv_label_create(ui_Power);
    lv_obj_set_width(ui_PowerSubTextTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerSubTextTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerSubTextTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerSubTextTag, "kW");
    lv_obj_set_style_text_font(ui_PowerSubTextTag, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed = lv_obj_create(ui_CarStats);
    lv_obj_remove_style_all(ui_Speed);
    lv_obj_set_height(ui_Speed, 225);
    lv_obj_set_width(ui_Speed, lv_pct(33));
    lv_obj_set_x(ui_Speed, 14);
    lv_obj_set_y(ui_Speed, -49);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Speed, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Speed, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Speed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Speed, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Speed, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Speed, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedTag = lv_label_create(ui_Speed);
    lv_obj_set_width(ui_SpeedTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedTag, "Speed");
    lv_obj_set_style_text_font(ui_SpeedTag, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBaseTag = lv_label_create(ui_Speed);
    lv_obj_set_width(ui_SpeedBaseTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedBaseTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedBaseTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedBaseTag, "80");
    lv_obj_set_style_text_font(ui_SpeedBaseTag, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedSubTextTag = lv_label_create(ui_Speed);
    lv_obj_set_width(ui_SpeedSubTextTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedSubTextTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedSubTextTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedSubTextTag, "km/h");
    lv_obj_set_style_text_font(ui_SpeedSubTextTag, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_obj_create(ui_CarStats);
    lv_obj_remove_style_all(ui_RPM);
    lv_obj_set_height(ui_RPM, 225);
    lv_obj_set_width(ui_RPM, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_x(ui_RPM, -366);
    lv_obj_set_y(ui_RPM, -49);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RPM, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_RPM, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RPM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_RPM, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RPM, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorTag = lv_label_create(ui_RPM);
    lv_obj_set_width(ui_MotorTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorTag, "Motor");
    lv_obj_set_style_text_font(ui_MotorTag, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorBaseTag = lv_label_create(ui_RPM);
    lv_obj_set_width(ui_MotorBaseTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorBaseTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorBaseTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorBaseTag, "400");
    lv_obj_set_style_text_font(ui_MotorBaseTag, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorSubTextTag = lv_label_create(ui_RPM);
    lv_obj_set_width(ui_MotorSubTextTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorSubTextTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorSubTextTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorSubTextTag, "RPM");
    lv_obj_set_style_text_font(ui_MotorSubTextTag, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Throttle = lv_obj_create(ui_CarStats);
    lv_obj_remove_style_all(ui_Throttle);
    lv_obj_set_height(ui_Throttle, 225);
    lv_obj_set_width(ui_Throttle, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_x(ui_Throttle, -366);
    lv_obj_set_y(ui_Throttle, -49);
    lv_obj_set_align(ui_Throttle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Throttle, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Throttle, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Throttle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Throttle, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Throttle, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThrottleTag = lv_label_create(ui_Throttle);
    lv_obj_set_width(ui_ThrottleTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThrottleTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ThrottleTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThrottleTag, "Throttle");
    lv_obj_set_style_text_font(ui_ThrottleTag, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThrottleBaseTag = lv_label_create(ui_Throttle);
    lv_obj_set_width(ui_ThrottleBaseTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThrottleBaseTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ThrottleBaseTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThrottleBaseTag, "33%");
    lv_obj_set_style_text_font(ui_ThrottleBaseTag, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThrottleSubTextTag = lv_label_create(ui_Throttle);
    lv_obj_set_width(ui_ThrottleSubTextTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThrottleSubTextTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ThrottleSubTextTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThrottleSubTextTag, "");

    ui_StateofCharge = lv_obj_create(ui_CarStats);
    lv_obj_remove_style_all(ui_StateofCharge);
    lv_obj_set_height(ui_StateofCharge, 225);
    lv_obj_set_width(ui_StateofCharge, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_x(ui_StateofCharge, -1358);
    lv_obj_set_y(ui_StateofCharge, 323);
    lv_obj_set_align(ui_StateofCharge, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StateofCharge, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_StateofCharge, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_StateofCharge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_StateofCharge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_StateofCharge, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateofChargeTag = lv_label_create(ui_StateofCharge);
    lv_obj_set_width(ui_StateofChargeTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateofChargeTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StateofChargeTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateofChargeTag, "Battery");
    lv_obj_set_style_text_font(ui_StateofChargeTag, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCBaseTag = lv_label_create(ui_StateofCharge);
    lv_obj_set_width(ui_SOCBaseTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOCBaseTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOCBaseTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOCBaseTag, "100%");
    lv_obj_set_style_text_font(ui_SOCBaseTag, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatterySubTextTag = lv_label_create(ui_StateofCharge);
    lv_obj_set_width(ui_BatterySubTextTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatterySubTextTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatterySubTextTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatterySubTextTag, "");

    ui_Brake = lv_obj_create(ui_CarStats);
    lv_obj_remove_style_all(ui_Brake);
    lv_obj_set_height(ui_Brake, 225);
    lv_obj_set_width(ui_Brake, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_x(ui_Brake, -366);
    lv_obj_set_y(ui_Brake, -49);
    lv_obj_set_align(ui_Brake, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Brake, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Brake, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Brake, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Brake, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Brake, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Brake, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrakeTag = lv_label_create(ui_Brake);
    lv_obj_set_width(ui_BrakeTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrakeTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrakeTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrakeTag, "Brake");
    lv_obj_set_style_text_font(ui_BrakeTag, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrakeBaseTag = lv_label_create(ui_Brake);
    lv_obj_set_width(ui_BrakeBaseTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrakeBaseTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrakeBaseTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrakeBaseTag, "67%");
    lv_obj_set_style_text_font(ui_BrakeBaseTag, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrakeSubTextTag = lv_label_create(ui_Brake);
    lv_obj_set_width(ui_BrakeSubTextTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrakeSubTextTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrakeSubTextTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrakeSubTextTag, "");

    ui_TemperatureContainer = lv_obj_create(ui_BaseContainer);
    lv_obj_remove_style_all(ui_TemperatureContainer);
    lv_obj_set_height(ui_TemperatureContainer, 561);
    lv_obj_set_width(ui_TemperatureContainer, LV_SIZE_CONTENT);   /// 133
    lv_obj_set_x(ui_TemperatureContainer, 237);
    lv_obj_set_y(ui_TemperatureContainer, 5);
    lv_obj_set_align(ui_TemperatureContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TemperatureContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TemperatureContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_TemperatureContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_TemperatureContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TemperatureTag = lv_label_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_TemperatureTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TemperatureTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureTag, "Temp.");
    lv_obj_set_style_text_font(ui_TemperatureTag, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureBaseTag = lv_label_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_TemperatureBaseTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureBaseTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureBaseTag, 7);
    lv_obj_set_y(ui_TemperatureBaseTag, -83);
    lv_obj_set_align(ui_TemperatureBaseTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureBaseTag, "67 °C");
    lv_obj_set_style_text_font(ui_TemperatureBaseTag, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureBar = lv_bar_create(ui_TemperatureContainer);
    lv_bar_set_value(ui_TemperatureBar, 67, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TemperatureBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TemperatureBar, 50);
    lv_obj_set_height(ui_TemperatureBar, 448);
    lv_obj_set_x(ui_TemperatureBar, 383);
    lv_obj_set_y(ui_TemperatureBar, 21);
    lv_obj_set_align(ui_TemperatureBar, LV_ALIGN_CENTER);

    lv_obj_set_style_radius(ui_TemperatureBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TemperatureBar, lv_color_hex(0xF95336), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TemperatureBar, lv_color_hex(0xD0F936), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TemperatureBar, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_TemperatureBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_TemperatureBar,
                                                                                                     lv_obj_get_style_pad_right(ui_TemperatureBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    uic_Container1 = ui_CarStateContainer;
    uic_TemperatureBar = ui_TemperatureBar;

}

void ui_DriverDisplay_screen_destroy(void)
{
    if(ui_DriverDisplay) lv_obj_del(ui_DriverDisplay);

    // NULL screen variables
    ui_DriverDisplay = NULL;
    ui_StatBase = NULL;
    ui_DescriptionTag = NULL;
    ui_StatBaseTag = NULL;
    ui_SubTextTag = NULL;
    ui_BaseContainer = NULL;
    uic_Container1 = NULL;
    ui_CarStateContainer = NULL;
    ui_VehicleStateLabel = NULL;
    ui_VehicleStateText = NULL;
    ui_CarStats = NULL;
    ui_Power = NULL;
    ui_PowerTag = NULL;
    ui_PowerBaseTag = NULL;
    ui_PowerSubTextTag = NULL;
    ui_Speed = NULL;
    ui_SpeedTag = NULL;
    ui_SpeedBaseTag = NULL;
    ui_SpeedSubTextTag = NULL;
    ui_RPM = NULL;
    ui_MotorTag = NULL;
    ui_MotorBaseTag = NULL;
    ui_MotorSubTextTag = NULL;
    ui_Throttle = NULL;
    ui_ThrottleTag = NULL;
    ui_ThrottleBaseTag = NULL;
    ui_ThrottleSubTextTag = NULL;
    ui_StateofCharge = NULL;
    ui_StateofChargeTag = NULL;
    ui_SOCBaseTag = NULL;
    ui_BatterySubTextTag = NULL;
    ui_Brake = NULL;
    ui_BrakeTag = NULL;
    ui_BrakeBaseTag = NULL;
    ui_BrakeSubTextTag = NULL;
    ui_TemperatureContainer = NULL;
    ui_TemperatureTag = NULL;
    ui_TemperatureBaseTag = NULL;
    uic_TemperatureBar = NULL;
    ui_TemperatureBar = NULL;

}
