// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_DriverDisplay = NULL;
lv_obj_t * ui_Speed = NULL;
// event funtions
void ui_event_DriverDisplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Speed, _UI_LABEL_PROPERTY_TEXT, "Updated Text");
    }
}

// build funtions

void ui_DriverDisplay_screen_init(void)
{
    ui_DriverDisplay = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DriverDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed = lv_label_create(ui_DriverDisplay);
    lv_obj_set_width(ui_Speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed, "This text is a placeholder");
    lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DriverDisplay, ui_event_DriverDisplay, LV_EVENT_ALL, NULL);

}

void ui_DriverDisplay_screen_destroy(void)
{
    if(ui_DriverDisplay) lv_obj_del(ui_DriverDisplay);

    // NULL screen variables
    ui_DriverDisplay = NULL;
    ui_Speed = NULL;

}
