// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_DRIVERDISPLAY_H
#define UI_DRIVERDISPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DriverDisplay
extern void ui_DriverDisplay_screen_init(void);
extern void ui_DriverDisplay_screen_destroy(void);
extern void ui_event_DriverDisplay(lv_event_t * e);
extern lv_obj_t * ui_DriverDisplay;
extern lv_obj_t * ui_Speed;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

